[package]
name = "test_crate"
version = "0.1.0"
edition = "2024"

[dependencies]
debug_with_context = { path = ".."}

[workspace]

[patch.crates-io]
debug_with_context_macros = { path = "../debug_with_context_macros" }
