[package]
name = "debug_with_context_macros"
version = "0.1.2"
edition = "2024"
description = "DO NOT USE : this is only for use with the debug_with_context macro"
license = "GPL-3.0-only"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.104"
